### ISSUE TITLE
2.27 - completely blank

### ISSUE THREAD

**Issue by krchristie** [geneontology/paint#38]
Hi Suzi,

I just downloaded this and launched it today (had some prior commitments Monday & Tuesday).

According to the console log, it is very fast, but the PAINT window that opens is just a blank gray window with a header bar no matter what I do. PAINT isn't actually crashed, as various menu commands open and/or work, including "Quit PAINT" under File, "Color selection..." under Edit, and  "New" under Annotate. However, even once the console indicates that it is finished opening all data, the PAINT window remains a blank and gray (see attached jpg).

I did download and use the new launchPAINT.bat and launchPAINT.sh files that come with the new paint-all.jar-27 file, but using my previous .bat and .sh files that I have been using with b25 don't have any effect on this issue.

Here is the console log from a session where I launched PAINT2.27 using the launchPAINT.sh file that came with it. Once the blank PAINT window appeared, I used the "New" command to load PTHR24056. The console said it had "Completed loading and initializing all data for PTHR24056" in less than a minute and stopped recording any new actions. In this case, I waited at least 10 minutes (long enough to load an even bigger family using 2.25) before quitting (using the menu command) just in case it needed longer to finish since the blankness of the PAINT window meant I couldn't see from it if any action was still in progress.

<pre>
bash-3.2$ pwd
/Applications/paint2.0-beta27
bash-3.2$ ll
total 151704
drwxr-xr-x  11 krc   admin            374 Nov 16 09:31 .
drwxrwxr-x+ 95 root  admin           3230 Nov 16 09:41 ..
-rw-r--r--@  1 krc   admin           6148 Nov 16 09:30 .DS_Store
-rw-------@  1 krc   admin            153 Oct  1  2015 b25-launchPAINT.bat
-rwx--x--x@  1 krc   admin             63 Oct  1  2015 b25-launchPAINT.sh
-rw-r--r--@  1 krc   1088672553       154 Nov 16 08:52 b27-launchPAINT.bat
-rwxr-xr-x@  1 krc   1088672553        64 Nov 16 08:47 b27-launchPAINT.sh
drwxr-xr-x   3 krc   admin            102 Nov 16 08:56 config
-rw-r--r--@  1 krc   admin            154 Nov 16 08:52 launchPAINT.bat
-rwxr-xr-x@  1 krc   admin             64 Nov 16 08:47 launchPAINT.sh
-rw-r--r--@  1 krc   1088672553  77638271 Nov 16 09:25 paint-all.jar
bash-3.2$ ./launchPAINT.sh
2016-11-16 10:14:00,461 INFO  (PaintYaml:45) Trying config found at: config/preferences.yaml
2016-11-16 10:14:00,493 INFO  (PaintYaml:50) Using config found at: config/preferences.yaml
2016-11-16 10:14:00,559 INFO  (PaintStartupTask:203) Loading Paint version 2.27
2016-11-16 10:14:01,438 WARN  (class:426) loadPerspectives: exception trying to create perspectives file config/perspectives/perspectives.xml from resourceconfig/perspectives/perspectives.xml
java.io.FileNotFoundException: cant get resource /config/perspectives/perspectives.xml
                               at org.bbop.io.FileUtil.findInputStream(FileUtil.java:98)
                               at org.bbop.io.FileUtil.ensureExists(FileUtil.java:69)
                               at org.bbop.io.FileUtil.ensureExists(FileUtil.java:36)
                               at org.bbop.framework.dock.idw.IDWDriver.loadPerspectives(IDWDriver.java:423)
                               at org.bbop.framework.dock.idw.IDWDriver.init(IDWDriver.java:607)
                               at org.bbop.framework.ComponentManager.setDriver(ComponentManager.java:85)
                               at org.bbop.framework.AbstractApplicationStartupTask.run(AbstractApplicationStartupTask.java:172)
                               at org.bbop.framework.AbstractSingleActionTask.install(AbstractSingleActionTask.java:24)
                               at org.bbop.framework.GUIManager.installTask(GUIManager.java:163)
                               at org.bbop.framework.GUIManager.start(GUIManager.java:236)
                               at org.paint.main.PAINT$2.run(PAINT.java:81)
                               at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
                               at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
                               at java.awt.EventQueue.access$500(EventQueue.java:97)
                               at java.awt.EventQueue$3.run(EventQueue.java:709)
                               at java.awt.EventQueue$3.run(EventQueue.java:703)
                               at java.security.AccessController.doPrivileged(Native Method)
                               at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
                               at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
                               at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
                               at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                               at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                               at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                               at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                               at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2016-11-16 10:14:13,938 INFO  (PantherServerAdapter:369) Logging in to Panther URL:  http://paintcuration.usc.edu
2016-11-16 10:14:14,035 INFO  (LoginUtil:74) dev_3_panther_upl|UPL 11.0
2016-11-16 10:14:14,037 INFO  (LoginUtil:93) Logging into PANTHER server
2016-11-16 10:14:14,039 INFO  (PantherServerAdapter:309)   opening connection 0 min, 0 sec
2016-11-16 10:14:14,039 INFO  (PantherServerAdapter:327)    sending request 0 min, 0 sec
2016-11-16 10:14:14,138 INFO  (PantherServerAdapter:336)     reading servlet output 0 min, 0 sec
2016-11-16 10:14:14,141 INFO  (PantherServerAdapter:340)      closing connnection to servlet 0 min, 0 sec
2016-11-16 10:14:14,142 INFO  (LoginUtil:109) Logged into PANTHER server 0 min, 0 sec
2016-11-16 10:14:22,524 INFO  (OWLutil:148) Begin loading GO
2016-11-16 10:14:22,654 INFO  (ParserWrapper:67) Start loading ontology: http://purl.obolibrary.org/obo/go.obo from: http://purl.obolibrary.org/obo/go.obo
2016-11-16 10:14:33,730 INFO  (ParserWrapper:74) Finished loading ontology: http://purl.obolibrary.org/obo/go.owl from: http://purl.obolibrary.org/obo/go.obo
2016-11-16 10:14:33,732 INFO  (OWLutil:153) GO retrieved 0 min, 11 sec
2016-11-16 10:14:34,044 INFO  (Reasoner:117) ELK reasoner was created
2016-11-16 10:14:39,457 INFO  (LoggingStageExecutor:70) Loading of Axioms started
2016-11-16 10:14:39,465 INFO  (AbstractReasonerStage:161) Loading of Axioms using 8 workers
2016-11-16 10:14:39,990 WARN  (ChangeIndexingProcessor:66) ELK does not support InverseObjectProperties. Axiom ignored:
InverseObjectProperties(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/BFO_0000051>)
2016-11-16 10:14:42,506 INFO  (LoggingStageExecutor:103) Loading of Axioms took 3042 ms
2016-11-16 10:14:42,507 INFO  (LoggingStageExecutor:70) Property Saturation Initialization started
2016-11-16 10:14:42,507 INFO  (AbstractReasonerStage:161) Property Saturation Initialization using 8 workers
2016-11-16 10:14:42,508 INFO  (LoggingStageExecutor:103) Property Saturation Initialization took 1 ms
2016-11-16 10:14:42,508 INFO  (LoggingStageExecutor:70) Reflexive Property Computation started
2016-11-16 10:14:42,511 INFO  (AbstractReasonerStage:161) Reflexive Property Computation using 8 workers
2016-11-16 10:14:42,513 INFO  (LoggingStageExecutor:103) Reflexive Property Computation took 4 ms
2016-11-16 10:14:42,513 INFO  (LoggingStageExecutor:70) Object Property Hierarchy and Composition Computation started
2016-11-16 10:14:42,515 INFO  (AbstractReasonerStage:161) Object Property Hierarchy and Composition Computation using 8 workers
2016-11-16 10:14:42,520 INFO  (LoggingStageExecutor:103) Object Property Hierarchy and Composition Computation took 6 ms
2016-11-16 10:14:42,520 INFO  (LoggingStageExecutor:70) Context Initialization started
2016-11-16 10:14:42,521 INFO  (AbstractReasonerStage:161) Context Initialization using 8 workers
2016-11-16 10:14:42,522 INFO  (LoggingStageExecutor:103) Context Initialization took 2 ms
2016-11-16 10:14:42,523 INFO  (LoggingStageExecutor:70) Consistency Checking started
2016-11-16 10:14:42,527 INFO  (AbstractReasonerStage:161) Consistency Checking using 8 workers
2016-11-16 10:14:42,589 INFO  (LoggingStageExecutor:103) Consistency Checking took 66 ms
2016-11-16 10:14:42,589 INFO  (LoggingStageExecutor:70) Class Taxonomy Computation started
2016-11-16 10:14:42,595 INFO  (AbstractReasonerStage:161) Class Taxonomy Computation using 8 workers
2016-11-16 10:14:49,277 INFO  (LoggingStageExecutor:103) Class Taxonomy Computation took 6687 ms
2016-11-16 10:14:49,509 INFO  (OWLutil:177) GO relations loaded 0 min, 26 sec
2016-11-16 10:14:53,020 INFO  (PaintPantherAdapter:62) Fetching PTHR24056 raw tree
2016-11-16 10:14:54,903 INFO  (PaintPantherAdapter:71) Loaded PTHR24056: 0 min, 1 sec
2016-11-16 10:14:55,561 INFO  (PaintManager:245) Completed loading and initializing all data for PTHR24056 in 0 min, 2 sec
2016-11-16 10:30:53,640 INFO  (GUIManager:305) Exiting.
</pre>
![20161116-b27-blanklaunch](https://cloud.githubusercontent.com/assets/10533218/20360688/8a2199d8-abe9-11e6-81ff-d987daf9f36a.jpg)

**Comment by selewis** [comment]
Goodness, we'll need to get together on line to track this down.

Anyone else have the same problem?


On Wed, Nov 16, 2016 at 10:46 AM, Karen R Christie <notifications@github.com

**Comment by selewis** [comment]
Wait, this is really simple.

Where did you put the jar file? It needs to be in the same directory where
your existing config directory is located. I took a screenshot of my
terminal window to show what your directory might look like.

It's not showing anything because it needs your personal layout information
to know where to put things. You could do this from the interface itself,
but simpler just to move things where they need to be.

-S

**Comment by krchristie** [comment]
Thanks for looking into this so quicky Suzi.  I thought this was going to solve it. That was the cause of the blankness, but restoring missing files in config directory hasn't solved everything. I normally duplicate the whole directory and rename it before putting the new jar file it it, but I did it slightly differently this time and forgot to copy the component_prefs and perspectives directories into the new directory. Duplicating the ones from my 2.25 directory and putting them into my 2.27 config directory solves the problem of the window being completely blank. When I first launch 2.27, I get the normal view without anything loaded.

However, now, when the console tells me that it is done, the PAINT window still looks like nothing is loaded. This is the entire console output from launch to exit. This log was for PTHR24056, which is pretty large, but I get the same result for a very small family, PTHR43590.

-Karen

<pre>
bash-3.2$ ./launchPAINT.sh
2016-11-16 13:54:33,444 INFO  (PaintYaml:45) Trying config found at: config/preferences.yaml
2016-11-16 13:54:33,477 INFO  (PaintYaml:50) Using config found at: config/preferences.yaml
2016-11-16 13:54:33,546 INFO  (PaintStartupTask:203) Loading Paint version 2.27
2016-11-16 13:54:35,742 INFO  (class:571) View #4, Garbage0, is a garbage view--destroying
2016-11-16 13:56:35,951 INFO  (PantherServerAdapter:369) Logging in to Panther URL:  http://paintcuration.usc.edu
2016-11-16 13:56:36,826 INFO  (LoginUtil:74) dev_3_panther_upl|UPL 11.0
2016-11-16 13:56:36,827 INFO  (LoginUtil:93) Logging into PANTHER server
2016-11-16 13:56:36,829 INFO  (PantherServerAdapter:309)   opening connection 0 min, 0 sec
2016-11-16 13:56:36,829 INFO  (PantherServerAdapter:327)    sending request 0 min, 0 sec
2016-11-16 13:56:37,266 INFO  (PantherServerAdapter:336)     reading servlet output 0 min, 0 sec
2016-11-16 13:56:37,269 INFO  (PantherServerAdapter:340)      closing connnection to servlet 0 min, 0 sec
2016-11-16 13:56:37,269 INFO  (LoginUtil:109) Logged into PANTHER server 0 min, 0 sec
2016-11-16 13:57:03,865 INFO  (OWLutil:148) Begin loading GO
2016-11-16 13:57:03,969 INFO  (ParserWrapper:67) Start loading ontology: http://purl.obolibrary.org/obo/go.obo from: http://purl.obolibrary.org/obo/go.obo
2016-11-16 13:58:25,273 INFO  (ParserWrapper:74) Finished loading ontology: http://purl.obolibrary.org/obo/go.owl from: http://purl.obolibrary.org/obo/go.obo
2016-11-16 13:58:25,274 INFO  (OWLutil:153) GO retrieved 1 min, 21 sec
2016-11-16 13:58:25,558 INFO  (Reasoner:117) ELK reasoner was created
2016-11-16 13:58:30,515 INFO  (LoggingStageExecutor:70) Loading of Axioms started
2016-11-16 13:58:30,524 INFO  (AbstractReasonerStage:161) Loading of Axioms using 8 workers
2016-11-16 13:58:31,156 WARN  (ChangeIndexingProcessor:66) ELK does not support InverseObjectProperties. Axiom ignored:
InverseObjectProperties(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/BFO_0000051>)
2016-11-16 13:58:35,103 INFO  (LoggingStageExecutor:103) Loading of Axioms took 4581 ms
2016-11-16 13:58:35,103 INFO  (LoggingStageExecutor:70) Property Saturation Initialization started
2016-11-16 13:58:35,104 INFO  (AbstractReasonerStage:161) Property Saturation Initialization using 8 workers
2016-11-16 13:58:35,105 INFO  (LoggingStageExecutor:103) Property Saturation Initialization took 1 ms
2016-11-16 13:58:35,105 INFO  (LoggingStageExecutor:70) Reflexive Property Computation started
2016-11-16 13:58:35,108 INFO  (AbstractReasonerStage:161) Reflexive Property Computation using 8 workers
2016-11-16 13:58:35,110 INFO  (LoggingStageExecutor:103) Reflexive Property Computation took 4 ms
2016-11-16 13:58:35,110 INFO  (LoggingStageExecutor:70) Object Property Hierarchy and Composition Computation started
2016-11-16 13:58:35,112 INFO  (AbstractReasonerStage:161) Object Property Hierarchy and Composition Computation using 8 workers
2016-11-16 13:58:35,117 INFO  (LoggingStageExecutor:103) Object Property Hierarchy and Composition Computation took 6 ms
2016-11-16 13:58:35,117 INFO  (LoggingStageExecutor:70) Context Initialization started
2016-11-16 13:58:35,118 INFO  (AbstractReasonerStage:161) Context Initialization using 8 workers
2016-11-16 13:58:35,119 INFO  (LoggingStageExecutor:103) Context Initialization took 2 ms
2016-11-16 13:58:35,119 INFO  (LoggingStageExecutor:70) Consistency Checking started
2016-11-16 13:58:35,124 INFO  (AbstractReasonerStage:161) Consistency Checking using 8 workers
2016-11-16 13:58:35,191 INFO  (LoggingStageExecutor:103) Consistency Checking took 71 ms
2016-11-16 13:58:35,191 INFO  (LoggingStageExecutor:70) Class Taxonomy Computation started
2016-11-16 13:58:35,196 INFO  (AbstractReasonerStage:161) Class Taxonomy Computation using 8 workers
2016-11-16 13:58:41,263 INFO  (LoggingStageExecutor:103) Class Taxonomy Computation took 6072 ms
2016-11-16 13:58:41,489 INFO  (OWLutil:177) GO relations loaded 1 min, 37 sec
2016-11-16 13:58:45,165 INFO  (PaintPantherAdapter:62) Fetching PTHR24056 raw tree
2016-11-16 13:58:45,169 INFO  (PaintPantherAdapter:71) Loaded PTHR24056: 0 min, 0 sec
2016-11-16 13:58:47,125 INFO  (PaintManager:245) Completed loading and initializing all data for PTHR24056 in 0 min, 1 sec
2016-11-16 14:19:41,803 INFO  (GUIManager:305) Exiting.
</pre>

**Comment by selewis** [comment]
Did you choose to load from a local file or from the server? (for the tree)

**Comment by krchristie** [comment]
So, far, I've only been trying load using the "New" command.

**Comment by selewis** [comment]
Okay,

Skype?

**Comment by selewis** [comment]
Same as issue #39
